<<<<<<< HEAD
site_name: OpenWorm
theme: readthedocs
pages:
  - [index.md, Home]
  - [intro.md, Introduction]
  - [background.md, Background]
  - [community.md, Community]
  - [faq.md, FAQ]
  - [fullhistory.md, History]
  - [releases.md, Releases]
  - [modeling.md, Modelling]
  - [Projects/, Projects]
=======
site_name: My Docs
>>>>>>> 5d2f2af7344e798ba4a0ded55235adf437570bba
