site_name: OpenWorm
theme: readthedocs
pages:
  - [index.md, Index]
  - [intro.md, Introduction]
  - [background.md, Background]
  - [fullhistory.md, History]
  - [releases.md, Releases]
  - [modeling.md, Modelling]
  - [Projects/projects.md, Projects, Projects]
  - [Projects/muscle-neuron-integration.md, Projects, Projects, Unifying Muscle and Cell Models]
  - [Projects/model-completion-dashboard.md, Projects, Projects, Model Completion Dashboard]
  - [Projects/sibernetic.md, Projects, Sibernetic]
  - [Projects/geppetto.md, Projects, Geppetto]
  - [Projects/worm-movement.md, Projects, Movement]
  - [Projects/optimization.md, Projects, Optimization]
  - [Projects/datarep.md, Projects, Representation]
  - [Projects/community-proj.md, Projects, Community]
  - [Community/community.md, Community, Community]
  - [Community/github.md, Community, Github]
  - [Community/repositories.md, Community, Repos]
  - [Community/membership.md, Community, Membership]
  - [Resources/resources.md, Resources, Resources]
  - [Resources/running-nc.md, Resources, Running NeuroConstruct]
  - [faq.md, FAQ]
